version: '3'

# This docker-compose file is intended to be used from the parent directory
# that contains both the trading-strategy-backtester and frontend directories
# 
# Example usage:
# Place this file in the parent directory as docker-compose.yml
# Run with: docker-compose up

services:
  backtester:
    build:
      context: ./trading-strategy-backtester
      dockerfile: Dockerfile
    volumes:
      - ./trading-strategy-backtester/input:/app/trading-strategy-backtester/input
      - ./trading-strategy-backtester/output:/app/trading-strategy-backtester/output
      - ./trading-strategy-backtester/logs:/app/trading-strategy-backtester/logs
      - ./trading-strategy-backtester/cache:/app/trading-strategy-backtester/cache
      - shared-data:/app/trading-strategy-backtester/output/shared
    environment:
      - BASE_DIR=/app/trading-strategy-backtester
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - shared-data:/app/frontend/public/data
    depends_on:
      - backtester
    networks:
      - app-network

volumes:
  shared-data:

networks:
  app-network:
    driver: bridge